import { Toaster } from '@/components/ui/sonner'
import { LOCALES } from '@/constants/i18n'
import ConvexClientProvider from '@/providers/convex-client-provider'
import { ModalProvider } from '@/providers/modal-provider'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, unstable_setRequestLocale } from 'next-intl/server'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/providers/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    'google-site-verification': 'EYz-pvIEKRcdhEso6BXEckhtfjVWnaWRVJf1eKdjIJ0'
  }
}

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  unstable_setRequestLocale(locale)
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>
            <NextIntlClientProvider messages={messages}>
              {children}
              <Toaster />
              <ModalProvider />
            </NextIntlClientProvider>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
